### ISSUE TITLE
CSV parser fails if only connections_saving_path_and_filename is commented

### ISSUE THREAD

**Issue by henhok** [sivanni/CxSystem#39]
AssertionError: The brian_data file cannot be found for loading

This also happens if both connections_saving_... and connections_loading_... are NOT commented. Weird, eh?

No connections are loaded (load_connection & save_connection ZERO everywhere)

**Comment by Vafa-Andalibi** [comment]
This is not actually an issue, the reason it's raising the error is because the file for loading the connections doesn't exist. It's the same when both of them are not commented. So you should first run the CxSystem with only "connections_saving_path_and_filename" set , and then use that file to load the connections. (and/or save the new connections at the same time, i.e. uncommenting both connections_saving_path_and_filename and connections_loading_path_and_filename)
